### ISSUE TITLE
[SUGGESTION] Hide Inactive

### ISSUE THREAD

**Issue by 9ryex5** [krbz999/visual-active-effects#11]
Please add the option not to show inactive effects when they have a duration.

**Comment by krbz999** [comment]
Would that not make it inconvenient to re-enable them? I'm wondering what your use case is for this.

**Comment by 9ryex5** [comment]
I have many active effects that are activated with the use of an item, upon receiving a condition, etc.
Very few require the players to activate them manually, so their screen will be cleaner if they don't see inactive effects.

The main reason i'm using this module (and maybe more people too) is so that players don't forget to deactivate effects they have active for awhile and not to activate effects.
