### ISSUE TITLE
foundry hud weblate

### ISSUE THREAD

**Issue by eunaumtenhoid** [krbz999/visual-active-effects#30]
hi, is it possible to add your mods to foundry hud weblate for us to translate or update the translation faster? https://weblate.foundryvtt-hub.com/

**Comment by krbz999** [comment]
Sure thing. Done.

**Comment by krbz999** [comment]
VAE has been submitted to weblate, but it's simply taking a while. Hopefully not much longer.

**Comment by krbz999** [comment]
Just confirming that VAE is now on weblate.
