### ISSUE TITLE
Prevent refreshing the application while it is being hovered over due to time advancing

### ISSUE THREAD

**Issue by Fatalmac77** [krbz999/visual-active-effects#35]
Very good module, I really like it.  The only problem I have is when i have Simple Calendar running, both icons and effect descriptions blink. They blink after hovering over them, as if they were refreshing on a regular basis.  It is related to refreshing Simple Calendar - set every 1 second causes blinking and refreshing of effect icons.
When the game is paused or during a fight - everything is fine. 
 Is there any way to solve this problem?

**Comment by krbz999** [comment]
Likely the css not playing nice with getting refreshed every single second.

**Comment by Fatalmac77** [comment]
All in all it will be easier to set the refresh to 60 seconds, then it's
fine.  All in all Calendar refresh is not needed every 1 second.  Thank you
for your answer.

pt., 17 mar 2023, 15:20 użytkownik Zhell ***@***.***> napisał:

**Comment by krbz999** [comment]
In the v11 release, the application will not refresh visually while hovered over. Ending the hover state will immediately refresh it (if there have been "pending" rendering calls).

**Comment by krbz999** [comment]
## Implemented feature:
While the panel is being hovered over, certain hooks will not refresh (re-render) the application. Some still will, such as updates to active effects and token selection, but updates to time will not. The application will remember if such a hook tried to render it, and will refresh once the user leaves the application (mouseout).

**Comment by jared112git** [comment]
Hi @krbz999, 
I believe I'm having this issue even with the latest updates. Here is a video of the VAE effect blinking each second. It's not urgent but kind of annoying out of combat as you can't read a VAE without pausing the game/calendar or opening the sheet. 
[Simple Calendar Example.webm](https://github.com/krbz999/visual-active-effects/assets/134901291/6f0b211d-f80b-4cc7-9cb4-0ba9e1522617)
I'm using:
VAE - 10.0.18
Simple Calendar - 2.3.13
Foundry - 10.291
DnD5e - 2.2.1

Any help would be greatly appreciated and please let me know if you need any further info.

**Comment by krbz999** [comment]
You are on the latest update compatible with Foundry Version 10. This issue was closed as part of VAE v11.0.0.
