### ISSUE TITLE
The effects do not appear on Forge accounts

### ISSUE THREAD

**Issue by V3rotti** [krbz999/visual-active-effects#39]
Visual Effects are not showing at all for me. 
![image](https://user-images.githubusercontent.com/56869989/233578788-fc6f858b-82f1-42be-b4b9-5f03e20e44a8.png)
Effects on the char are present, but not showing in the corner.
Module Version is 10.0.16
Tested without other modules active.

**Comment by V3rotti** [comment]
tested with VAE active only - same result
![image](https://user-images.githubusercontent.com/56869989/233621954-d884eca5-9a60-4056-af8b-d8513e08eddf.png)
don't know what you mean by VAE settings do not look like that
Console does not show any errors on effect application or deletion.

**Comment by InnilToo** [comment]
In the first screenshot, you are showing the VAE settings. Those settings are different from what the actual module's setting looks like (yours have some weird icons), which makes me think something else has interfered with the module.
I would recommend making a new world and only enabling VAE to test it.

**Comment by krbz999** [comment]
Let's move troubleshooting to a better suited location.
Module server: https://discord.gg/QAG8eWABGT

**Comment by krbz999** [comment]
Discovered that this was a Forge issue since they reorder the modules' files, so rather than
```
modules/visual-active-effects/styles/visual-active-effects.css
```
they allocate it with the version number appended:
```
modules/visual-active-effects/v10.0.15/styles/visual-active-effects.css
```
