### ISSUE TITLE
Effects don't show up on Forge

### ISSUE THREAD

**Issue by Wolkei** [krbz999/visual-active-effects#40]
The effects don't show up at all on the top right.

Console gives the following error: 

![error](https://user-images.githubusercontent.com/38896855/233797132-9738ba97-d55f-44b8-9070-e9f6a2e35531.png)

The issue doesn't occur on v10.0.14, but does on v10.0.15-v10.0.17
Using Firefox and hosting on Forge, tested without any other modules running on a new world, as well as with all browser extensions disabled.

**Comment by Shayulghul** [comment]
I'm having the same issue with a slightly different error:
- Foundry 10.291
- DnD5e 2.1.5
- Chrome 112.0.5615.137
- VAE is only module enabled
- Works correctly in my Electron app

Error: Uncaught (in promise) DOMException: Failed to read the 'rules' property from 'CSSStyleSheet': Cannot access rules 
- at applyStyleSettings (https://assets.forge-vtt.com/bazaar/modules/visual-active-effects/10.0.17/scripts/helpers.mjs:113:38)
- at Object.fn (https://assets.forge-vtt.com/bazaar/modules/visual-active-effects/10.0.17/setup.mjs:10:3)
