### ISSUE TITLE
add all Effects to the combat tracker

### ISSUE THREAD

**Issue by patrickmohrmann** [krbz999/visual-active-effects#62]
It would be great, if all effects could be shown in the combat tracker with an additonal sign (may be numbers) to indicate how many rounds they have left.

**Comment by krbz999** [comment]
Hi there,

I'm afraid that would go beyond the scope of this module. It is purposefully limited to making a singular panel of effects in the upper right of the screen, not touching the combat tracker. :)

Changes to the combat tracker would be something a system could or should implement.

**Comment by patrickmohrmann** [comment]
ok, great to know, love it anyway a lot.
