### ISSUE TITLE
[Feature request] Support for the Cmd key to render effect's config

### ISSUE THREAD

**Issue by TrofimSelbs** [krbz999/visual-active-effects#64]
This module is a real game changer for me. Thank you, you have sped up my DMing significantly with this awesome module, and the ability to change position by pixels is super cool.

There is a feature that I would like to request. Would be cool if there was a quick way to open the effect's settings quickly and change them from there. For example with Shift+left mouse click. Thank you for your work

**Comment by krbz999** [comment]
Check the readme, this is already a feature.

**Comment by TrofimSelbs** [comment]
You are right! I see, I have only checked in module settings, will do better next time.
Unfortunately, this doesn't work for me, as I am on Mac platform. If I ⌘Command + left click on it two times it disables the effect. If I Ctrl+left click on it - it asks to delete the effect. Could you please add support for it?

**Comment by TrofimSelbs** [comment]
thank you 🙏

**Comment by krbz999** [comment]
Should be added in 11.1.4.

**Comment by TrofimSelbs** [comment]
thanks!
