### ISSUE TITLE
[Feature Request] Hide Extra Details

### ISSUE THREAD

**Issue by NdranC** [krbz999/visual-active-effects#67]
The module automatically adds the entire description of the item that created the effect to that effect's description. This has caused several issues where players spoiled themselves by reading what a skill from a creature does before they shouldn't. It would be nice if there was a toggle to prevent this.

**Comment by krbz999** [comment]
> The module automatically adds the entire description of the item that created the effect to that effect's description.

This would certainly be news to me.

**Comment by NdranC** [comment]
Sorry I have so many modules so perhaps I'm mistaken but doesn't this module add this description to the effects?
![image](https://github.com/user-attachments/assets/0cb979be-7a35-4479-b7fa-ef82045a7ad5)

The "No" is the actual effect description,  the "details" is the description of the skill that made this effect.
![image](https://github.com/user-attachments/assets/9e18c3ee-6c46-4929-8dbd-75241ddb4df7)
If I try to see the effect tooltip any other way then it doesn't show up the "details"

**Comment by krbz999** [comment]
If you have a lot of modules and you suspect there is an issue with a single one of them, the first thing you should do is disable all but that one. Then see if the issue persists.

**Comment by NdranC** [comment]
Unfortunately I have tried. I've been using "Find the culprit!" but every time I run it I've gotten 2 different results "Warpgate" and "Monk's Active Tiles". Which tells me that there must be something wrong with the methodology I'm using to test the issue every time. I'm using the midiqol automation ecosystem so I'm sure one of them might be the culprit but is hard to find since all of them depend heavily on each other and several features break if one of them is disabled.

My best guess was that it was this mod since it only shows up in your mod's tooltip and nowhere else and if I turn off your mod then I can't test if the issue goes away or not. Thank you anyway.

**Comment by chrisk123999** [comment]
The module Chris's Premades adds that as an optional setting. You would have had to explicitly turn on that setting in module integration.

**Comment by NdranC** [comment]
Thank you for replying to this. Can you tell me where this setting is located? I might be blind but I checked and couldn't find it.

**Comment by chrisk123999** [comment]
Settings -> Chris's Premades -> Module Integration

**Comment by NdranC** [comment]
Omg that's what VAE stands for... I'll admit, perhaps at some point I knew that but since then I guess I forgot. I can even see you added a setting to selectively disable this setting for NPCs like I want.

Thank you for checking and posting a solution for my dim witted problem. I don't think I would have found it if it wasn't for you.
