### ISSUE TITLE
PHB2024 - Old 2014 Reference in Exhaustion Tooltip

### ISSUE THREAD

**Issue by Kapuzenjoe** [krbz999/visual-active-effects#72]
Hello,
I noticed the following flaw with VAE and the PHB2024 module. When I assign the exhaustion effect to a character, the VAE tooltip shows me the reference to the old (2014) rules, but not to the new (2024).

The effect itself works perfectly according to the new rules. (as far as I know this is enabled via the system core)
![grafik](https://github.com/user-attachments/assets/39d07696-1883-4985-be97-0cd24eadf0bd)

Is it possible to reference the new rules when the PHB2024 module is active? Or that you can select the preferred reference in the settings?

Foundry: Version 12.331
5e-System: Version 4.0.4
VAE: Version: 12.1.1 

![grafik](https://github.com/user-attachments/assets/32801c95-4a72-40e7-9dd8-12c6676eb2af)

![grafik](https://github.com/user-attachments/assets/f51f59db-cc51-4303-85ee-24c6c769d42c)

**Comment by krbz999** [comment]
Would be an issue with the PHB module or the dnd5e system. This module does not decide what description is available, it only reads what is provided.
