### ISSUE TITLE
Force a Refresh without changing token.

### ISSUE THREAD

**Issue by matthewbstroud** [krbz999/visual-active-effects#73]
Can you expose an API that would allow a forced redraw?  I am dynamically changing some effect icons and updated the document immediately redraws on the token, but not on VAE.

**Comment by krbz999** [comment]
Updating an effect should already be refreshing the panel, as seen [here](https://github.com/krbz999/visual-active-effects/blob/main/scripts/setup.mjs#L17).

**Comment by matthewbstroud** [comment]
In this case, I am updating the effect on an _item_ that is apply the effect to the actor.  So the effect parent is the _item_, no the actor.  So the panel doesn't refresh.
![image](https://github.com/user-attachments/assets/511d172b-67a1-4f9a-87e4-e3d9e16fa7ad)

**Comment by matthewbstroud** [comment]
I was able to cobble this together, but is pretty hacky...

```js
async function changeHealth(actorUuid, health) {
        let actor = await fromUuid(actorUuid);
        let horse = getHorse(actor);
        let effect = horse.effects.find(e => e.name == "Mounted");
        if (!effect) {
            return false;
        }
        let icon = `modules/stroud-dnd-helpers/images/icons/saddle_health/saddle_health_${health}.webp`;
        await horse.updateEmbeddedDocuments("ActiveEffect", [{ "_id": effect.id, "icon": icon }])
        let style = $(`div[data-effect-uuid='${effect.uuid}'] div.effect-icon`).attr("style");
        style = style.replace(/modules\/stroud-dnd-helpers\/images\/icons\/saddle_health\/saddle_health_\d{2}\.webp/, icon);
        $(`div[data-effect-uuid='${effect.uuid}'] div.effect-icon`).attr("style", style);
    }
```

**Comment by krbz999** [comment]
What version of the module are you using?

**Comment by matthewbstroud** [comment]
11.0.6

**Comment by matthewbstroud** [comment]
I am getting ready to migrate to V12 though...  Maybe I will just live with the hack for now.

**Comment by krbz999** [comment]
The current version should already be supporting this (see the above link to the current code, it is `effect.target` rather than `effect.parent`).
