### ISSUE TITLE
Unable to hide Active Effects provided by enchantments

### ISSUE THREAD

**Issue by Katalyst8095** [krbz999/visual-active-effects#76]
Foundry v12 331
D&D 4.1.1
Modules active: 2024 PHB, TCE, VAE

Issue
Active effects granted by enchantments as visible with all hide options enabled, they cannot be force hidden or force displayed as they do not appear on the effects tab of the character sheet. This occurs with and without a duration on the granted effect. 

Reproduce
Enchant a weapon using the True Strike cantrip provided in the PHB. This also occurs with a new Enchant Activity from a blank feature.

![Screenshot 2024-11-17 092402](https://github.com/user-attachments/assets/68685750-9ebb-4ac3-89ce-daf817269fba)

Thank you for the module, it has been fantastic for QOL while running a game to have effects and their tooltips readily accessible.

**Comment by krbz999** [comment]
"Secondary" type effects, such as enchantments in the dnd5e system, are now split into three sections akin to the primary ones (those on the actor directly).

- Temporary, enabled effects. Shown by default.
- Temporary, disabled effects. Shown by default according to setting.
- Passive effects. Never shown unless individually forced.
