### ISSUE TITLE
At lower resolution, the attack dialogue can be off screen.

### ISSUE THREAD

**Issue by Stonedtroll** [krbz999/visual-active-effects#78]
At 1080p

![](https://gitlab.com/-/project/20418308/uploads/218e694e160436c6c0f85bcec578cae1/image.png)

Issue was first opened with Midi-QOL but it was pointed out that perhaps it is better handled here.

https://gitlab.com/tposney/midi-qol/-/issues/1461

**Comment by thatlonelybugbear** [comment]
Well you weren't pointed to this repository!

But to Advantage Reminder module... <https://github.com/kaelad02/adv-reminder>

**Comment by Stonedtroll** [comment]
Wrong repo...sorry

**Comment by krbz999** [comment]
It's important to know what your modules do.

**Comment by Stonedtroll** [comment]
My apologies again. I knew that it wasn't this module but just came from updating this module so it was on my mind. Put it down to having your great work always on my mind <3.
